//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace XExtention
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ExFloat
	{
		public virtual void ToByte()
		{
			throw new System.NotImplementedException();
		}

		public virtual void ToDouble()
		{
			throw new System.NotImplementedException();
		}

		public virtual void ToInt()
		{
			throw new System.NotImplementedException();
		}

		public virtual void ToObject()
		{
			throw new System.NotImplementedException();
		}

	}
}

