//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MessagesControl
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Xprema;

	public class MessageOperation:XpremaBaseClass
	{
        private static string _SaveingMessage;
        private static string _SavedMessage;

        public static void ini()
        {
            if (SelectedLanguge == XLanguge.Arabic)
            {
                _SaveingMessage = "..جاري الحفظ";
                _SavedMessage = "تم الحفظ بنجاح";
            }
            else
            {
                _SaveingMessage = "Saveing..";
                _SavedMessage = "Saved successfully";
            }
        }
		public static string  SaveingMessage
		{
			get{
            return _SaveingMessage;
            }
			
		}

		public virtual object SavedMessage
		{
			get;
			set;
		}

		public virtual object DeletedMessage
		{
			get;
			set;
		}

		public virtual object DeleteMessage
		{
			get;
			set;
		}

		public virtual object SaveErrorMessage
		{
			get;
			set;
		}

		public virtual object DeleteingMessage
		{
			get;
			set;
		}

		public virtual object EditingMessage
		{
			get;
			set;
		}

		public virtual object EditedMessage
		{
			get;
			set;
		}

	}
}

