//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MessagesControl
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Xprema;

	public class MessageOperation:XpremaBaseClass
	{
        private static string _SaveingMessage;
        private static string _SavedMessage;
        private static string _DeletedMessage;
        private static string _DeleteingMessage;
        private static string _WhatDelete;

        public static void ini()
        {
            if ( XpremaBaseClass.SelectedLanguge == XLanguge.Arabic)
            {
                _SaveingMessage = "..جاري الحفظ";
                _SavedMessage = "تم الحفظ بنجاح";
                SaveErrorMessage = " لسوء الحظ حدث خطأ اثناء عمليةالحفظ";
                //******************************************************
                _DeletedMessage = "تم الحذف بنجاح";
                _DeleteingMessage = "جاري الحذف..";
                _WhatDelete = "هل تريد الحذف؟";
                //***************************************************
                EditingMessage = "جاري التعديل";
                EditedMessage = "تم التعديل بنجاح";

                
            }
            else
            {
                _SaveingMessage = "Saveing..";
                _SavedMessage = "Saved successfully";
                SaveErrorMessage = "Oh, Some Error/s While Saveing";
                //*********************************************************
                //******************************************************
                _DeletedMessage = "Deleted..";
                _DeleteingMessage = "Deleteing Now ...";
                _WhatDelete = "Want To Delete?";

                //***************************************************
                EditingMessage = "Editing Now ...";
                EditedMessage = "Edit Successfully..";

            }

           
        }
		public static  string  SaveingMessage
		{
			get{
            return _SaveingMessage;
            }
			
		}

		public static  string  SavedMessage
		{
            get
            {
                return _SavedMessage;
            }
			
		}

		public static  string  DeletedMessage
		{
			 get
             {
                return _DeletedMessage;
             }
		}

		public static  string  DeleteMessage
		{
            get
            {
                return _DeleteingMessage ;
            }
		}

        public static  string DeleteWhatToDeleteMessage
        {
            get
            {
                return _WhatDelete;
            }
        }

		public static  string  SaveErrorMessage
		{
			get;
			set;
		}

		public static  string  EditingMessage
		{
			get;
			set;
		}

		public static  string  EditedMessage
		{
			get;
			set;
		}

	}
}

